name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Update libusb submodule (android branch)
        run: |
          cd app/src/main/cpp/libusb
          git fetch origin
          git checkout -B android origin/android
          git reset --hard origin/android
          cd -

      - name: Update libxml2 submodule (lineage-20.0 branch)
        run: |
          cd app/src/main/cpp/libxml2
          git fetch origin
          git checkout -B lineage-20.0 origin/lineage-20.0
          git reset --hard origin/lineage-20.0
          cd -

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/src/main/cpp/libusb app/src/main/cpp/libxml2
          git commit -m "chore: update submodules to latest branch commit" || echo "No changes to commit"
          git push
